name: macOS App Bundles
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    name: Build macos-14-universal

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./SDL3-3.2.10.dmg
            ./SDL3_image-3.2.4.dmg
            ./SDL3_mixer-3.0.1.dmg
            ./SDL3_ttf-3.2.0.dmg
            ./gstreamer-1.0-1.22.12-universal.pkg
            ./gstreamer-1.0-devel-1.22.12-universal.pkg
          key: macos-dependencies-${{ hashFiles('**/build-appbundle.yml') }}
          restore-keys: |
            macos-dependencies-

      - name: Download dependencies
        run: |
          if [ ! -f "SDL3-3.2.10.dmg" ]; then
            curl -LO https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-3.2.10.dmg
          fi
          if [ ! -f "SDL3_image-3.2.4.dmg" ]; then
            curl -LO https://github.com/libsdl-org/SDL_image/releases/download/release-3.2.4/SDL3_image-3.2.4.dmg
          fi
          if [ ! -f "SDL3_mixer-3.0.1.dmg" ]; then
            curl -LO https://github.com/libsdl-org/SDL_mixer/releases/download/release-3.0.1/SDL3_mixer-3.0.1.dmg
          fi
          if [ ! -f "SDL3_ttf-3.2.0.dmg" ]; then
            curl -LO https://github.com/libsdl-org/SDL_ttf/releases/download/release-3.2.0/SDL3_ttf-3.2.0.dmg
          fi
          if [ ! -f "gstreamer-1.0-1.22.12-universal.pkg" ]; then
            curl -LO https://gstreamer.freedesktop.org/data/pkg/osx/1.22.12/gstreamer-1.0-1.22.12-universal.pkg
          fi
          if [ ! -f "gstreamer-1.0-devel-1.22.12-universal.pkg" ]; then
            curl -LO https://gstreamer.freedesktop.org/data/pkg/osx/1.22.12/gstreamer-1.0-devel-1.22.12-universal.pkg
          fi

      - name: Install GStreamer packages
        run: |
          sudo installer -pkg gstreamer-1.0-1.22.12-universal.pkg -target /
          sudo installer -pkg gstreamer-1.0-devel-1.22.12-universal.pkg -target /

      - name: Attach and copy SDL3 framework
        run: |
          hdiutil attach SDL3-3.2.10.dmg
          cp -R /Volumes/SDL3/SDL3.framework RetroFE/ThirdPartyMac/
          hdiutil detach /Volumes/SDL3

      - name: Attach and copy SDL3_image framework
        run: |
          hdiutil attach SDL3_image-3.2.4.dmg
          cp -R /Volumes/SDL3_image/SDL3_image.framework RetroFE/ThirdPartyMac/
          cp -R /Volumes/SDL3_image/optional/webp.framework RetroFE/ThirdPartyMac/
          hdiutil detach /Volumes/SDL3_image

      - name: Attach and copy SDL3_mixer framework
        run: |
          hdiutil attach SDL3_mixer-3.0.1.dmg
          cp -R /Volumes/SDL3_mixer/SDL3_mixer.framework RetroFE/ThirdPartyMac/
          hdiutil detach /Volumes/SDL3_mixer

      - name: Attach and copy SDL3_ttf framework
        run: |
          hdiutil attach SDL3_ttf-3.2.0.dmg
          cp -R /Volumes/SDL3_ttf/SDL3_ttf.framework RetroFE/ThirdPartyMac/
          hdiutil detach /Volumes/SDL3_ttf

      - name: Copy GStreamer framework
        run: | 
          cp -R /Library/Frameworks/GStreamer.framework RetroFE/ThirdPartyMac/

      - name: Debug - get size
        run: |
          du -sh RetroFE/ThirdPartyMac/*

      - name: Install Homebrew dependencies
        run: |
          brew install minizip create-dmg

      - name: Build project with Xcode
        run: | 
          xcodebuild -project RetroFE/xcode/retrofe.xcodeproj

      - name: Debug - get size
        run: |
          du -sh RetroFE/Build/Release/RetroFE.app

      - name: Post build GStreamer.framework slimming
        run: | 
          chmod +x Scripts/macOS/delete_gstreamer_unused_libs.sh
          Scripts/macOS/delete_gstreamer_unused_libs.sh RetroFE/Build/Release/RetroFE.app/Contents/Frameworks/GStreamer.framework/Versions/1.0/lib
          rm -rf RetroFE/Build/Release/RetroFE.app/Contents/Frameworks/GStreamer.framework/Versions/1.0/include

      - name: Debug - get size
        run: |
          du -sh RetroFE/Build/Release/RetroFE.app

      - name: Create RetroFE.dmg
        run: | 
          create-dmg "RetroFE.dmg" RetroFE/Build/Release/    
      
      - name: Upload RetroFE.dmg
        uses: actions/upload-artifact@v4
        with:
          name: RetroFE.dmg
          path: RetroFE.dmg

          
